#:kivy 1.11.1
<MyWidget>

    name: name
    age: age


    GridLayout:
        cols: 1
        size: root.width - 200, root.height - 200
        pos: 100, 100

        GridLayout:
            cols: 2

            Label:
                text: "Name: "
            TextInput:
                multiline: False

            Label:
                text: "Age: "
            TextInput:
                multiline: False

        Button:
            text: "Submit"